import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./_store/StoreProvider";
import ConditionalLayoutRendering from "./_Components/ConditionalLayoutRendering/ConditionalLayoutRendering";

export const metadata: Metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="h-screen flex flex-col">
          <ConditionalLayoutRendering>{children}</ConditionalLayoutRendering>
        </body>
      </html>
    </StoreProvider>
  );
}
