import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import StoreProvider from "../reduxStore/StoreProvider";
import ConditionalLayoutRendering from "../components/ConditionalLayoutRendering/ConditionalLayoutRendering";
import BootstrapClient from "@/components/UI/BootstrapClient/BootstrapClient";

export const metadata: Metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="h-screen flex flex-col">
          <ConditionalLayoutRendering>{children}</ConditionalLayoutRendering>
        </body>
      </html>
    </StoreProvider>
  );
}
